frontend/modules/sections/controllers/AuditController.php
<?php

namespace app\modules\sections\controllers;

use app\components\Api;
use app\modules\sections\models\audit\CreateForm;
use app\modules\sections\models\audit\JobAudit;
use app\modules\sections\models\audit\ListAudits;
use app\modules\sections\models\audit\PartitionsAudits;
use app\modules\sections\models\audit\ProcessAudit;
use yii\base\InvalidParamException;
use yii\web\Controller;
use yii\web\HttpException;

class AuditController extends Controller
{
    public function behaviors()
    {
        return [
            'isAjax' => [
                'class' => 'frontend\behaviors\AjaxBehavior',
                'actionsUsed' => ['process', 'list']
            ],
        ];
    }

    public function actionIndex()
    {
        $form = new CreateForm();
        $pagination = \Yii::$app->request->getBodyParams()
            ? \Yii::$app->request->getBodyParams()
            : [
                'per-page' => 5, 'page' => 1
            ];
        $listModel = ListAudits::model($pagination);
        $audits = PartitionsAudits::model();
        if (\Yii::$app->request->getBodyParams()) {
            $form->load(\Yii::$app->request->getBodyParams());
            if ($form->validate()) {
                $queryParams = $form->getAttributes();
                $queryParams['usedAudit'] = $queryParams['useAudit'];
                unset($queryParams['useAudit']);
                $res = Api::resource('audit')->post($queryParams);
                if (!isset($res->error)) {
                    $form = new CreateForm();
                } elseif ($res->validateError) {
                    $job = new CreateForm();
                    $job->errors = $res->error->message;
                    return $job;
                } else {
                    throw new HttpException($res->error->status, $res->error->message);
                }
            }
        }
        return $this->render(
            'index', [
                'model' => $form, 'audits' => $audits,
                'listModel' => $listModel,
                'processModel' => (new ProcessAudit())->getAttributes()
            ]
        );

    }

    public function actionList()
    {
        $params = \Yii::$app->request->getBodyParams();
        return $this->renderPartial('items', ['model' => ListAudits::model($params)]);
    }

    public function actionJobs()
    {
        $params = \Yii::$app->request->getBodyParams();
        return $this->renderPartial('job', ['model' => JobAudit::model($params['id'], $params)]);
    }

    public function actionProcess()
    {
        if (!$id = \Yii::$app->request->getBodyParam('audit')) {
            throw new InvalidParamException('Missing require param {audit}');
        }
        $model = ProcessAudit::model($id);
        return $this->renderPartial('process', ['model' => $model]);
    }
}

frontend/modules/sections/views/audit/index.php
<?php
use \app\modules\sections\assets\AssetsAudit;
use \frontend\widgets\ActiveItemsList\ActiveItemsListWidget;
?>
<div class="container-fluid">
    <div class="row">
        <?= $this->render('form/create',['model'=>$model,'audits'=>$audits])?>
    </div>
    <div class="row" id="content">
        <div class="col-md-12">
            <div class="container-fluid list-orders-audit" id="list-orders-audit">
                <?php ActiveItemsListWidget::begin([
                        'listModel' => '\app\modules\sections\models\audit\ListAudits',
                        'template' => '@sections/views/audit/audit_list/header.php',
                        'templateItem' => '@sections/views/audit/audit_list/items.php',
                        'isAjax' => true,
                        'options' => [
                            'id'=>'list-orders-audit'
                        ],
                        'clientOptions' => [
                            'page' =>1,
                            'pageSize' =>5,
                            'itemsAction' => Yii::$app->urlManager->createAbsoluteUrl('/audit/list'),
                            'headerClass' => "list-audit-header"
                        ]
                    ]
                )->end();
                ?>
            </div>
        </div>
    </div>
</div>
<?php
AssetsAudit::register($this);
?>

frontend/modules/sections/views/audit/items.php
<?php foreach ($model as $line): ?>
    <div class="row exist-item-audit list-records">
        <div class="col-md-1 id-list-audit">
            <div class="unique-audit-item id"> <?= $line->id ?></div>
        </div>
        <div class="col-md-5 name-list-audit">
            <div class="name-audit-item customer_name"> <?= $line->customer_name ?></div>
            <div class="url-audit-item url"> <?= $line->url ?></div>
        </div>
        <div class="col-md-2 status-list-audit status">
            <?= $line->status ?>
        </div>
        <div class="col-md-2 date-list-audit created_time">
            <?= $line->created_time ?>
        </div>
        <div class="col-md-2 date-list-audit updated_time">
            <?= $line->updated_time ?>
        </div>
    </div>
    <div class="row process-items-audit">
        <span class="found exists-audit" id="list-item-<?= $line->id ?>"></span>
    </div>

<?php endforeach; ?>

frontend/modules/sections/views/audit/job.php
<?php foreach ($model as $line): ?>
<div class="row attach-audits">
    <div class="col-md-1 att-id id"><?= $line->id;?></div>
    <div class="col-md-5 att-comment "><?= $line->subscribe;?></div>
    <div class="col-md-2 att-status status"><?= $line->status;?></div>
    <div class="col-md-2 att-date created_time"><?= $line->created_time;?></div>
    <?php if ($line->url):?>
        <div class="col-md-2 att-href url"><a class="href" href="<?= $line->url;?>">PDF FILE</a></div>
    <?php endif; ?>
</div>
<?php endforeach; ?>

frontend/modules/sections/views/audit/process.php
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 process-partition-audits">
            <label for="process-partition-audits" class="label-default">
                Список заказанных уадитов
            </label>
            <ul id="process-partition-audits">
                <?php foreach($model->partitions as $line):?>
                <li><?= $line->name?><span class="price"><?= $line->price.Yii::t('sections',$line->currency)?></span></li>
                <?php
                    $currency = $line->currency;
                endforeach;
                ?>
                <li><?= Yii::t('audit','Total:')?><span class="price"><?= $model->price_total.Yii::t('sections',$currency)?></span></li>

            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 process-about-audits">
            <?php if(isset($model->products)):?>
            <label for="process-about-audits" class="label-default">
                Товары и услуги
            </label>
            <div id="process-about-audits-extra-info" class="about-audits">
                <?=$model->products; ?>
            </div>
            <?php endif; ?>
            <?php if(isset($model->target_audience)):?>
            <label for="process-about-audits" class="label-default">
                Целевая уадитория
            </label>
            <div id="process-about-audits-extra-info" class="about-audits">
                <?=$model->target_audience; ?>
            </div>
            <?php endif; ?>
            <?php if(isset($model->site_competitors)):?>
            <label for="process-about-audits" class="label-default">
                Конкуренты сайта
            </label>
            <div id="process-about-audits-extra-info" class="about-audits">
                <?=$model->site_competitors; ?>
            </div>
            <?php endif; ?>
            <?php if(isset($model->promotion_problem)):?>
            <label for="process-about-audits" class="label-default">
                Проблеммы при продвижении
            </label>
            <div id="process-about-audits-extra-info" class="about-audits">
                <?=$model->promotion_problem; ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 process-attachments-audits" id="audit-job-<?= $model->id?>">
            <?php
            $id = $model->id;
            \frontend\widgets\ActiveItemsList\ActiveItemsListWidget::begin(
                [
                    'listModel' => 'app\modules\sections\models\audit\JobAudit',
                    'template' => '@sections/views/audit/job_list/header.php',
                    'templateItem' => '@sections/views/audit/job_list/items.php',
                    'options' => [
                        'id' => '#audit-job-'.$id
                    ],
                ]
            )->end();?>
        </div>
    </div>
</div>